---
title: "The Evolution of the Esports Industry"
author: "Mivelaz, Allan & van Kampen, Adrian"
date: ""
runtime: shiny
output: slidy_presentation
css: style.css
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
source(file = here::here("scripts/setup.R"))
```

## Our goals

- Identify potentially interesting areas of the E-sports ecosystem (games, tournaments, etc.)
- Show the popularity of streaming platforms
- Determine factors that influence gaming's popularity

## Data Sources

- [EsportsEarnings.com](http://www.esportsearnings.com)
- [TwitchTracker](https://www.twitchtracker.com)
- [Newzoo.com](https://platform.newzoo.com/explorer)

## E-sports earnings

```{r EE_data_import, include=FALSE}
source(file = here::here("scripts/Esport_earnings.R"))

top_plots <- list("NbTourn" = rankg_by_tournnb,
                  "Prizes" = rankg_by_prizes,
                  "PlayerNb" = rankg_by_playernb)

```

```{r game_ranks}
inputPanel(
  radioButtons(
    inputId = "EE_top_stats",
    label = "Top 5%",
    inline = TRUE,
    choices = c("Number of Tournaments", "Prizes", "Player numbers"),
    width = "100%"
  )
)


renderPlotly({

  if(input$EE_top_stats == "Number of Tournaments") {
    rankg_by_tournnb
  } else if(input$EE_top_stats == "Prizes") {
    rankg_by_prizes
  } else if(input$EE_top_stats == "Player numbers") {
    rankg_by_playernb
  }
})
```

## Tournaments through time


```{r}

tourn_selection <- o_tourn %>%
  filter(GameName %in% c("StarCraft II",
                         "League of Legends",
                         "Dota 2",
                         "Counter-Strike: Global Offensive",
                         "Fortnite",
                         "Super Smash Bros. Melee"))

inputPanel(
  selectInput(
    "GameNameBoth",
    label = "Game:",
    choices = tourn_selection$GameName, # N.B. I chose the list with top games in terms of tournament numbers, because it is the only one that contains all 5 games mentioned above. However, this is an arbitrary choice.
    selected = o_tourn$GameName[1]
  )
)

renderDygraph({
  
  plot_data <- tournaments %>%
    filter(GameId == o_tourn$GameId[o_tourn$GameName == input$GameNameBoth]) %>%
    group_by(Month_Yr = floor_date(EndDate, "month")) %>%
  summarize(prize = sum(TotalUSDPrize),
            tournb = n())
    
  prize_cash_xts <- xts(plot_data$prize, 
                        order.by = plot_data$Month_Yr)
  tourn_nb_xts <- xts(plot_data$tournb, 
                      order.by = plot_data$Month_Yr)
  
  both <- cbind(prize_cash_xts, tourn_nb_xts)
  dygraph(both) %>%
    dyRangeSelector() %>%
    dyAxis("y", independentTicks = FALSE) %>%
    dyAxis("y2", label = "Number of tournaments", independentTicks = TRUE) %>%
    dySeries("prize_cash_xts", label = "Prize Cash (in USD)") %>%
    dySeries("tourn_nb_xts", label = "Number of tournaments", axis = "y2") %>%
    dyHighlight(highlightCircleSize = 5, 
                highlightSeriesBackgroundAlpha = 0.2,
                hideOnMouseOut = FALSE) %>%
    dyLegend(width = 500) %>%
    dyOptions(labelsKMB = TRUE)
  
})

renderPlotly({
  
  top_tourn <- tournaments %>%
    filter(GameId == o_tourn$GameId[o_tourn$GameName == input$GameNameBoth]) %>%
    select(TournamentName, TotalUSDPrize, StartDate, EndDate, Location, Teamplay) %>%
    arrange(desc(TotalUSDPrize)) %>%
    head(n = 5) %>%
    # Make histogram of top tournaments
    ggplot(aes(x = reorder(TournamentName, TotalUSDPrize), y = TotalUSDPrize, fill = TotalUSDPrize)) +
    geom_col(show.legend = FALSE) +
    ggtitle(paste(input$GameNameBoth, "top tournament", sep = "'s ")) +
    xlab("") +
    ylab("Prize pool (in USD)") +
    scale_y_continuous(labels = unit_format(unit = "M", scale = 1e-6)) +
    coord_flip()
  
  # Wrap with ggplotly to make tooltips on hover
  
  ggplotly(top_tourn, tooltip = "y")
  
})
```
