## EDA for Twitch data-set

These data comes from the website : [Newzoo](https://platform.newzoo.com/explorer)

```{r, echo=FALSE, warning=FALSE, message=FALSE}
source(here::here("scripts/setup.R"))
```

```{r}
data2 <- read_delim(file = here::here("data/NZ_CompaniesPublicRevenues2.csv"), ";", escape_double = FALSE, col_names = FALSE, trim_ws = TRUE)

CompaniesPublicRevenues <- data2 %>%
  rename(Company_name = X1, Region_of_HQ = X2, Q1_2019 = X3, Q2_2019 = X4, Q3_2019 = X5, Q4_2019 = X6, Q1_2020 = X7, Q2_2020 = X8) %>%
  mutate(Q1_2019 = parse_number(Q1_2019), Q2_2019 = parse_number(Q2_2019), 
         Q3_2019 = parse_number(Q3_2019), Q4_2019 = parse_number(Q4_2019), 
         Q1_2020 = parse_number(Q1_2020), Q2_2020 = parse_number(Q2_2020)) %>%
  mutate(Q1_2019 = ifelse(Q1_2019 < 10 , Q1_2019*1000, Q1_2019), 
         Q2_2019 = ifelse(Q2_2019 < 10 , Q2_2019*1000, Q2_2019), 
         Q3_2019 = ifelse(Q3_2019 < 10 , Q3_2019*1000, Q3_2019), 
         Q4_2019 = ifelse(Q4_2019 < 10 , Q4_2019*1000, Q4_2019),
         Q1_2020 = ifelse(Q1_2020 < 10 , Q1_2020*1000, Q1_2020),
         Q2_2020 = ifelse(Q2_2020 < 10 , Q2_2020*1000, Q2_2020)) %>%
  mutate(First_semester_of_2019 = Q1_2019 + Q2_2020, 
         Second_semester_of_2019 = Q3_2019 + Q4_2019, 
         Total_in_2019 = Q1_2019 + Q2_2019 + Q3_2019 + Q4_2019, 
         First_semester_in_2020 = Q1_2020 + Q2_2020) %>%
  mutate(Q1_grate = 100*(Q1_2020 - Q1_2019)/Q1_2019, 
         Q2_grate = 100*(Q2_2020 - Q2_2019)/Q2_2019, 
         Semester2_grate = 100*(Second_semester_of_2019 - First_semester_of_2019)/First_semester_of_2019,
         Semester3_grate = 100*(First_semester_in_2020 - Second_semester_of_2019)/Second_semester_of_2019,
         First_semester_grate = 100*(First_semester_in_2020 - First_semester_of_2019)/First_semester_of_2019)

CompaniesPublicRevenues %>% 
   kbl(caption = "Twitch statistics") %>%  
   kable_paper(full_width = F) %>% 
   add_header_above(c(" " = 2, "2019" = 4, "2020" = 2, "Total per semester/year" = 4, "Growth rate" = 5)) %>%
   scroll_box(width = "100%", height = "300px")
```

```{r}
data3 <- read_delim(file = here::here("data/NZ_CompaniesInvestmentscsv1.csv"), ";", escape_double = FALSE, col_names = FALSE, trim_ws = TRUE)

data4 <- read_delim(file = here::here("data/NZ_CompaniesInvestmentscsv2.csv"), ";", escape_double = FALSE, col_names = FALSE, trim_ws = TRUE)

CompaniesInvestments <- data3 %>% full_join(data4) %>%
  rename(Date = X1, "Investment type" = X2, Sectors = X3, Emptycolumn = X4, Investee = X5, Amount = X6) %>%
  mutate(Date = dmy(Date), Emptycolumn = NULL, Sectors = str_replace_all(Sectors, ",.", ", "))


CompaniesInvestments %>% 
   kbl(caption = "Twitch statistics") %>%  
   kable_paper(full_width = F) %>% 
   scroll_box(width = "100%", height = "300px")
```