---
title: "Shiny Presentation test"
author: "Adrian"
date: "08-12-2020"
output: ioslides_presentation
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
source(here::here("scripts/setup.R"))
library(plotly)
```

## Shiny Presentation

This R Markdown presentation is made interactive using Shiny. The viewers of the presentation can change the assumptions underlying what's presented and see the results immediately. 

To learn more, see [Interactive Documents](http://rmarkdown.rstudio.com/authoring_shiny.html).

## Most valuable games

```{r value}
## Load data

tournaments <-
  read.csv(file = here::here("data/EsportsEarnings.com/EE_tournaments.csv"))

games <-
  read.csv(file = here::here("data/EsportsEarnings.com/EE_games_earnings.csv")) %>%
  rename(GameId = id) # We add this to harmonize variables name across datasets

## Clean data

# Get highest tournament number games

o_prizes <- games %>%
  select(GameId, GameName, TotalUSDPrize) %>%
  filter(TotalUSDPrize > quantile(TotalUSDPrize, p = 0.90, na.rm = TRUE)) %>%
  arrange(desc(TotalUSDPrize))

tourn_bygame1 <- tournaments %>%
  left_join(games, by = "GameId") %>%
  rename(TotalUSDPrize = TotalUSDPrize.x, X = X.x) %>%
  select(X:GameId,
         GameName,
         TournamentName:TotalUSDPrize) %>%
  mutate(StartDate = as_date(StartDate),
         EndDate = as_date(EndDate)) %>%
  filter(GameId %in% o_prizes$GameId) %>%
  group_by(Month_Yr = floor_date(EndDate, "month"), GameId) %>%
  summarize(prize = sum(TotalUSDPrize))

inputPanel(
  selectInput(
    "gameName",
    label = "Game:",
    choices = o_prizes$GameName,
    selected = o_prizes$GameName[1]
  ),
  
  sliderInput(
    "dateRange",
    label = "Date range of observations:",
    min = as.Date("2000-01-01", "%Y-%m-%d"),
    max = as.Date("2019-12-31", "%Y-%m-%d"),
    value = c(as.Date("2000-01-01"),
              as.Date("2019-12-31")),
    timeFormat = "%Y-%m-%d"
  )
)

renderPlotly({
  mainplot <- tourn_bygame1 %>%
    filter(GameId == o_prizes$GameId[o_prizes$GameName == input$gameName]) %>%
    filter(Month_Yr >= input$dateRange[1]) %>%
    filter(Month_Yr <= input$dateRange[2]) %>%
    ggplot(aes(x = Month_Yr, y = prize)) +
    geom_line() +
    ggtitle(paste("Total prize cash won: ",
                  paste(
                    format(
                      round(o_prizes$TotalUSDPrize[o_prizes$GameName == input$gameName] / 1e6, 1),
                      trim = TRUE,
                      digits = 6
                    ), "M"
                  ),
                  sep = "")) +
    xlab("") +
    ylab("") +
    xlim(input$dateRange[1], input$dateRange[2])
  
  ggplotly(mainplot)
})
```

## Number of tournaments per month

```{r number}
## Load data

tournaments <-
  read.csv(file = here::here("data/EsportsEarnings.com/EE_tournaments.csv"))

games <-
  read.csv(file = here::here("data/EsportsEarnings.com/EE_games_earnings.csv")) %>%
  rename(GameId = id) # We add this to harmonize variables name across datasets

## Clean data

# Get highest tournament number games

o_tourn <- games %>%
  select(GameId, GameName, TotalTournaments) %>%
  arrange(desc(TotalTournaments)) %>%
  filter(TotalTournaments > quantile(TotalTournaments, p = 0.95, na.rm =
                                       TRUE))


tourn_bygame <- tournaments %>%
  left_join(games, by = "GameId") %>%
  rename(TotalUSDPrize = TotalUSDPrize.x, X = X.x) %>%
  select(X:GameId,
         GameName,
         TournamentName:TotalUSDPrize) %>%
  mutate(StartDate = as_date(StartDate),
         EndDate = as_date(EndDate)) %>%
  filter(GameId %in% o_tourn$GameId) %>%
  group_by(Month_Yr = floor_date(EndDate, "month"), GameId) %>%
  summarize(number = n())

inputPanel(
  selectInput(
    "gameId",
    label = "Game ID to display:",
    choices = o_tourn$GameName,
    selected = o_tourn$GameName[1]
  ),
  
  sliderInput(
    "dateRange",
    label = "Date range of observations:",
    min = as.Date("2000-01-01", "%Y-%m-%d"),
    max = as.Date("2019-12-31", "%Y-%m-%d"),
    value = c(as.Date("2000-01-01"),
              as.Date("2019-12-31")),
    timeFormat = "%Y-%m-%d"
  )
)

renderPlot({
  tourn_bygame %>%
    filter(GameId == o_tourn$GameId[o_tourn$GameName == input$gameId]) %>%
    filter(Month_Yr >= input$dateRange[1]) %>%
    filter(Month_Yr <= input$dateRange[2]) %>%
    ggplot(aes(x = Month_Yr, y = number)) +
    geom_line() +
    ggtitle("Data source: esportsearnings.com") +
    xlab("") +
    ylab("") +
    xlim(input$dateRange[1], input$dateRange[2])
  
})
```