---
title: "An overview of the twitch platform"
author: "Mivelaz Allan"
date: "`r Sys.Date()`"
output:
  html_document:
    theme: readable
    toc: true
    toc_float: true
    number_sections: true
    runtime: shiny
---

```{r, echo = FALSE, message = FALSE, include=FALSE}
source(here::here("scripts/setup.R"))
```


```{r}
data1 <- read_delim(file = here::here("data/Twitch.csv"), ";", 
                    escape_double = FALSE, col_names = FALSE, trim_ws = TRUE)

# Data cleaning

TwitchData <- data1 %>%
  # set a name for each variable
  rename(Date = X1, Avg_concur_viewers = X2, 
         Avg_concur_channels = X3, Hours_watched = X4, 
         Active_streamers = X5, Hours_streamed = X6) %>%
  # modify the format of certain variable
  mutate(Date = mdy(Date), 
         Hours_watched = parse_number(Hours_watched)*1000000) %>%
  # Replace value with NA (in our dataframe, n/a are considered as character)
  replace_with_na(replace = list(Active_streamers = "n/a")) %>%
  mutate(Viewers_per_streamer = Hours_watched/Hours_streamed) %>%
  # Convert the column from character to double
  mutate(Active_streamers = parse_number(Active_streamers))

# Data overview

TwitchData %>%
  # shows values in a more aesthetic way
  mutate(Date = data1$X1,
         Avg_concur_viewers = case_when(Avg_concur_viewers >= 1000000000 ~ f_bills(Avg_concur_viewers, digits = 12),
                                                     Avg_concur_viewers >= 1000000 & Avg_concur_viewers < 1000000000 ~ f_mills(Avg_concur_viewers, digits = -4),
                                                     Avg_concur_viewers < 1000000 & Avg_concur_viewers >= 1000 ~ f_thous(Avg_concur_viewers, digits = 6)),
         Avg_concur_channels = case_when(Avg_concur_channels >= 1000000000 ~ f_bills(Avg_concur_channels, digits = 12),
                                         Avg_concur_channels >= 1000000 & Avg_concur_channels < 1000000000 ~ f_mills(Avg_concur_channels, digits = 9),
                                         Avg_concur_channels < 1000000 & Avg_concur_channels >= 1000 ~ f_thous(Avg_concur_channels, digits = -2)),
         Hours_watched = case_when(Hours_watched >= 1000000000 ~ f_bills(Hours_watched, digits = -7),
                                   Hours_watched >= 1000000 & Hours_watched < 1000000000 ~ f_mills(Hours_watched, digits = -3),
                                   Hours_watched < 1000000 & Hours_watched >= 1000 ~ f_thous(Hours_watched, digits = 6)),
         Active_streamers = case_when(Active_streamers >= 1000000000 ~ f_bills(Active_streamers, digits = 12),
                                      Active_streamers >= 1000000 & Active_streamers < 1000000000 ~ f_mills(Active_streamers, digits = -4),
                                      Active_streamers < 1000000 & Active_streamers >= 1000 ~ f_thous(Active_streamers, digits = 6)),
         Hours_streamed = case_when(Hours_streamed >= 1000000000 ~ f_bills(Hours_streamed, digits = 12),
                                    Hours_streamed >= 1000000 & Hours_streamed < 1000000000 ~ f_mills(Hours_streamed, digits = -4),
                                    Hours_streamed < 1000000 & Hours_streamed >= 1000 ~ f_thous(Hours_streamed, digits = 6)),
         Viewers_per_streamer = round(Viewers_per_streamer, digits = 1)) %>%
  rename("Concurrent viewers" = Avg_concur_viewers,
         "Concurrent channels" = Avg_concur_channels,
         "Active channels" = Active_streamers,
         "Hours watched" = Hours_watched,
         "Hours streamed" = Hours_streamed,
         "Viewers per streamer" = Viewers_per_streamer)
```

```{r}

# watched_xts <- xts(TwitchData$Hours_watched, order.by = TwitchData$Date)
# streamed_xts <- xts(TwitchData$Hours_streamed, order.by = TwitchData$Date)
# viewers_xts <- xts(TwitchData$Viewers_per_streamer, order.by = TwitchData$Date)
# 
# all <- cbind(watched_xts, streamed_xts, viewers_xts)
# 
# dygraph(all, height = 300) %>%
#   dyRangeSelector() %>%
#   dySeries("watched_xts", axis = "y") %>%
#   dySeries("streamed_xts", axis = "y") %>%
#   dySeries("viewers_xts", axis = "y2") %>%
#   dyAxis("y2", label = "Viewers per stream", independentTicks = TRUE) %>%
#   dyLegend(show = "follow") %>%
#   dyOptions(labelsKMB = TRUE, logscale = TRUE)
#   
# 
# 
plot_ly(data = TwitchData, x = ~TwitchData$Date, y = ~TwitchData$Hours_watched
        ,type = "scatter", mode = "lines", width = 800
        ,name = "Hours watched", height = 400) %>%
  add_trace(x = ~TwitchData$Date, y = ~TwitchData$Hours_streamed, yaxis = "y2", name = "Hours streamed") %>%
  add_trace(x = ~TwitchData$Date, y = ~TwitchData$Viewers_per_streamer, yaxis = "y3", name = "Viewers per steamers")%>%
  layout(
    yaxis = list(
      showline = FALSE, side = "left"
      ,title = ""
      , color = "blue"
    )
    ,yaxis2 = list(
      showline = FALSE
      ,overlaying = "y"
      ,title = ""
      , anchor = "free"
      , color = "orange"
    )
    ,yaxis3 = list(
      showline = FALSE,
      side = "right",
      overlaying = "y"
      ,title = ""
      , color = "green"
    )
    ,xaxis = list(
      showline = FALSE, zeroline = FALSE, dtick = 0, title = "Date"
    )
    ,showlegend = TRUE
    ,margin = list(
      pad = 30, b = 90, l = 150, r = 90
    )
    ,legend = list(orientation = "v")
    , title = "Comparaison between watched and streamed"
  )
```