---
title: "Your Document Title"
author: "Document Author"
date: "`r Sys.Date()`"
output:
  html_document:
    theme: readable
    toc: true
    toc_float: true
    number_sections: true
    runtime: shiny
---

```{r, echo = FALSE, message = FALSE, include=FALSE}
source(here::here("scripts/setup.R"))
```


```{r}
tournaments <- read_csv(file = here::here("data/EsportsEarnings.com/EE_tournaments.csv"))
```

```{r}
games <- read_csv(file = here::here("data/EsportsEarnings.com/EE_games_earnings.csv")) %>%
  rename(GameId = id) # We add this to harmonize variables name across datasets
```

```{r}
teams <- read_csv(file = here::here("data/EsportsEarnings.com/EE_teams_earnings.csv"))
```

```{r}
o_tourn <- games %>%
  select(GameId, GameName, TotalTournaments) %>%
  arrange(desc(TotalTournaments)) %>%
  filter(TotalTournaments > quantile(TotalTournaments, p=0.95, na.rm=TRUE))

```


```{r}
o_prizes <- games %>%
  select(GameId, GameName, TotalUSDPrize) %>%
  filter(TotalUSDPrize > quantile(TotalUSDPrize, p=0.95, na.rm=TRUE)) %>%
  arrange(desc(TotalUSDPrize))

```

```{r}

# Prepare data to display temporal stats by game
# gid <- 166
# 
# tourn_bygame2 <- tournaments %>%
#   left_join(games, by = "GameId") %>%
#   rename(TotalUSDPrize = TotalUSDPrize.x) %>% # We only want Total Prize by tournament, not by game
#   select(TournamentId:GameId,
#          GameName,
#          TournamentName:TotalUSDPrize) %>%
#   group_by(Month_Yr = floor_date(EndDate, "month"), GameId, GameName) %>%
#   summarize(prize = sum(TotalUSDPrize),
#             tournb = n()) %>%
#   filter(GameId == gid)
# 
# 
# prize_cash_xts <- xts(tourn_bygame2$prize, 
#                       order.by = tourn_bygame2$Month_Yr)
# tourn_nb_xts <- xts(tourn_bygame2$tournb, 
#                     order.by = tourn_bygame2$Month_Yr)
# 
# both <- cbind(prize_cash_xts, tourn_nb_xts)
# dygraph(both) %>%
#   dyRangeSelector()

```


```{r}
inputPanel(
  selectInput(
    "GameNameBoth",
    label = "Game:",
    choices = o_tourn$GameName, # N.B. I chose the list with top games in terms of tournament numbers, because it is the only one that contains all 5 games mentioned above. However, this is an arbitrary choice.
    selected = o_tourn$GameName[1]
  )
)

renderDygraph({
  
  plot_data <- tournaments %>%
    filter(GameId == o_tourn$GameId[o_tourn$GameName == input$GameNameBoth]) %>%
    group_by(Month_Yr = floor_date(EndDate, "month")) %>%
  summarize(prize = sum(TotalUSDPrize),
            tournb = n())
    
  prize_cash_xts <- xts(plot_data$prize, 
                        order.by = plot_data$Month_Yr)
  tourn_nb_xts <- xts(plot_data$tournb, 
                      order.by = plot_data$Month_Yr)
  
  both <- cbind(prize_cash_xts, tourn_nb_xts)
  dygraph(both) %>%
    dyRangeSelector() %>%
    dyAxis("y", label = "Prize Cash (in USD)") %>%
    dyAxis("y2", label = "Number of tournaments", independentTicks = TRUE) %>%
    dySeries("prize_cash_xts", label = "Prize Cash (in USD)") %>%
    dySeries("tourn_nb_xts", label = "Number of tournaments", axis = "y2") %>%
    dyHighlight(highlightCircleSize = 5, 
              highlightSeriesBackgroundAlpha = 0.2,
              hideOnMouseOut = FALSE) %>%
    dyLegend(width = 500)
  
})
```

